title: "Nathan Anderson – Computational Linguist"
description: "Computational Linguist | Language Technologies Product Manager | CMU-LTI Alum"
baseurl: ""
url: "https://yourusername.github.io"
theme: minima
